services:

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mwis-scraper
    env_file:
      - .env
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    command: >
      sh -c "
        python -m mwis_api.scraper.scrape &&
        while true; do
          sleep 3600
          python -m mwis_api.scraper.scrape
        done
      "
    depends_on:
      rabbitmq: 
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mwis-network

  rabbitmq:
    image: rabbitmq:management
    container_name: mwis-rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mwis-network

  worker:
    build:
      context: .
    container_name: mwis-worker
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    command: python -m mwis_api.worker.worker
    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mwis-network

  postgres:
    image: postgres:15-alpine
    container_name: mwis-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mwis-network
    restart: unless-stopped


  migrate:
    container_name: mwis-migrate
    build:
      context: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - mwis-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mwis-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      LOG_LEVEL: info
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    volumes:
      - ./mwis_api:/app/mwis_api
    command: uvicorn mwis_api.api.api:app --host 0.0.0.0 --port 8000
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/forecasts"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mwis-network


volumes:
  postgres_data:

networks:
  mwis-network:
    driver: bridge