[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mwis_api"
version = "0.1.1"
dependencies = [
    "fastapi",
    "uvicorn",
    "requests",
    "beautifulsoup4",
    "pika",
    "ipykernel", # temp
    "jsonschema",
    "pytest",
    "httpx2",
    "pandas",
    "tenacity",
    "testcontainers[rabbitmq]",
    "sqlalchemy",
    "psycopg2-binary",
    "sqlmodel",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["mwis_api"]
